name: Build APK Fastest

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/hearis71/android-builder:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify gradlew exists
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "‚ùå gradlew not found in root directory"
            exit 1
          fi

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Grant Execute Permission
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --parallel --build-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
